sudo: required
services:
- docker
language: python
python:
- '2.7'
install: true
script:
- ./docs/scripts/docker-docs.sh \
  pip install --user ./ \
  make -C docs/ html
deploy:
- provider: script
  skip_cleanup: true
  on:
    branch: v7.0
    repo: F5Networks/f5-openstack-heat-plugins
  script:
  - ./docs/scripts/deploy-docs.sh publish-product-docs-to-prod openstack/heat-plugins/kilo v7.0
